Repository hcsp/fix-inner-class-error, pull requests merged in 2019-10, with the labels that each got.

#47 docs(README): fix typo
  README.md
Labels: from:VIP, is:enhancement

#48 fix: fix inner class error
  src/main/java/com/github/hcsp/polymorphism/Home.java
  src/main/java/com/github/hcsp/polymorphism/Home2.java
Labels: from:VIP, is:answer

#49 fix-inner-class-error
  src/main/java/com/github/hcsp/polymorphism/Home.java
  src/main/java/com/github/hcsp/polymorphism/Home2.java
Labels: is:answer

#50 fix inner class error
  src/main/java/com/github/hcsp/polymorphism/Home.java
  src/main/java/com/github/hcsp/polymorphism/Home2.java
Labels: from:VIP, is:answer

#51 fix inner class error
  src/main/java/com/github/hcsp/polymorphism/Home.java
  src/main/java/com/github/hcsp/polymorphism/Home2.java
Labels: is:answer

#52 fix inner class error
  src/main/java/com/github/hcsp/polymorphism/Home.java
  src/main/java/com/github/hcsp/polymorphism/Home2.java
Labels: from:VIP, is:answer

#53 静态内部类和非静态内部类
  src/main/java/com/github/hcsp/polymorphism/Home.java
  src/main/java/com/github/hcsp/polymorphism/Home2.java
Labels: from:VIP, is:answer

#54 test
  src/main/java/com/github/hcsp/polymorphism/Home.java
  src/main/java/com/github/hcsp/polymorphism/Home2.java
Labels: is:answer

#55 内部类问题
  src/main/java/com/github/hcsp/polymorphism/Home.java
  src/main/java/com/github/hcsp/polymorphism/Home2.java
Labels: from:VIP, is:answer

#56 fix-inner-class-error
  src/main/java/com/github/hcsp/polymorphism/Home.java
  src/main/java/com/github/hcsp/polymorphism/Home2.java
Labels: from:VIP, is:answer

#57 fix: inner class error
  src/main/java/com/github/hcsp/polymorphism/Home.java
  src/main/java/com/github/hcsp/polymorphism/Home2.java
Labels: from:VIP, is:answer

#58 内部类
  src/main/java/com/github/hcsp/polymorphism/Home.java
  src/main/java/com/github/hcsp/polymorphism/Home2.java
Labels: from:VIP, is:answer

#59 修复内部类的问题
  src/main/java/com/github/hcsp/polymorphism/Home.java
  src/main/java/com/github/hcsp/polymorphism/Home2.java
Labels: from:VIP, is:answer

#60 内部类练习
  src/main/java/com/github/hcsp/polymorphism/Home.java
  src/main/java/com/github/hcsp/polymorphism/Home2.java
Labels: from:VIP, is:answer
